services:
  opensearch:
    image: opensearchproject/opensearch:2.19.4
    container_name: opensearch-local
    environment:
      - discovery.type=single-node
      # - plugins.security.disabled=true
      - plugins.security.disabled=false
      - plugins.security.allow_unsafe_democertificates=true
      - plugins.security.allow_default_init_securityindex=true
      - plugins.security.authcz.admin_dn=CN=admin,OU=SSL,O=Test,L=Test,C=DE
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m

      # dev only
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Admin123!DevOnly
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - opensearch-data:/usr/share/opensearch/data

volumes:
  opensearch-data:
